### ISSUE TITLE
Is xformers still not support cuda 12.0?

### ISSUE THREAD

**Issue by debdip** [facebookresearch/xformers#581]
# ❓ Questions and Help
I got the following error while installing...

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Obtaining file:///F:/Stable_Diffusion/stable-diffusion-webui-master/repositories/xformers
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [9 lines of output]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0'
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\setup.py", line 293, in
symlink_package(
File "F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\setup.py", line 83, in symlink_package
os.symlink(src=path_from, dst=path_to)
OSError: [WinError 1314] A required privilege is not held by the client: 'F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\third_party\flash-attention\flash_attn' -> 'F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\xformers\_flash_attn'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

Is it for cuda 12. Should I degrade the cuda version?

or what is the problem, can anyone help?

**Comment by danthe3rd** [comment]
We haven't tested CUDA 12.0 yet - I'm not even sure if it's supported by pytorch.
The error you get at the installation is unrelated tho, and will be fixed after https://github.com/facebookresearch/xformers/pull/582

**Comment by debdip** [comment]
just checked in pytorch website. 

they support till 11.7.

Then I have to reinstall 11.7 right?

**Comment by danthe3rd** [comment]
I wouldn't recommend 12.0 at the moment, but 11.7 is supported so yes you should install 11.7 if you can

**Comment by debdip** [comment]
Ok. 
I'll reinstall to 11.7 and check if that works.

**Comment by debdip** [comment]
**Facing this problem now.**

F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers>pip install -e .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///F:/Stable_Diffusion/stable-diffusion-webui-master/repositories/xformers
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\setup.py", line 293, in <module>
          symlink_package(
        File "F:\Stable_Diffusion\stable-diffusion-webui-master\repositories\xformers\setup.py", line 83, in symlink_package
          os.symlink(src=path_from, dst=path_to)
      OSError: [WinError 1314] A required privilege is not held by the client: 'F:\\Stable_Diffusion\\stable-diffusion-webui-master\\repositories\\xformers\\third_party\\flash-attention\\flash_attn' -> 'F:\\Stable_Diffusion\\stable-diffusion-webui-master\\repositories\\xformers\\xformers\\_flash_attn'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

please help.

**Comment by danthe3rd** [comment]
Apply this patch: https://github.com/facebookresearch/xformers/pull/582

**Comment by debdip** [comment]
Hello,

I tried with the patch but got an error again. I already changed my cuda version 11.7. 
This is the cmd output (It's very big). 
the last part error is 

 C:\Users\User\AppData\Local\Temp\tmpxft_00001a64_00000000-7_fmha_block_dgrad_fp16_kernel_loop.sm80.compute_86.cudafe1.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 4294967295

**Comment by debdip** [comment]
https://pastebin.com/Kc3TdbTw

**Comment by debdip** [comment]
**should I degrade again my cuda toolkit to like 11.6 or 11.4~11.5.?**

although pytorch support till 11.7 in there websites. 

pytorch with cuda version 11.7 working fine with cuda toolkit 12.0 I tested that with some simple code. 

but when **I try to run xformers setup.py then it showed version mismatch and I moved to 11.7 which match the pytorch version**. 

after that I got the latest error which pastebin link is given.

**Comment by danthe3rd** [comment]
CUDA 11.7 is fine. Your error is not due to the CUDA version, but looks specific to windows.
See also this: https://stackoverflow.com/questions/34074925/vs-2015-cannot-open-compiler-generated-file-invalid-argument
Unfortunately we don't really provide support for windows at the moment, so you will have to deal with this on your own :/

We're working on getting wheels to work on pypi, which should make it easy to install xformers directly from pip: https://github.com/facebookresearch/xformers/issues/533

**Comment by danthe3rd** [comment]
You can track the effort to release wheels in https://github.com/facebookresearch/xformers/issues/533, I don't have more information

**Comment by debdip** [comment]
Hello there
sorry to open this again. 
according to this [link](https://github.com/facebookresearch/xformers/issues/533) as the wheel uploaded i can install it right?

Is this have anything to worry about the xformers repositories that i have and my previous attempt?
