### ISSUE TITLE
Build with CUDA 12.6 and VS 2022 17.11.1 broken on Windows

### ISSUE THREAD

**Issue by levicki** [facebookresearch/xformers#1083]
# 🐛 Bug

I am trying to build xformers from the main branch and no matter whether I try `0.0.27.post2` tag or the latest commit I am getting build errors.

## Command

git clone https://github.com/facebookresearch/xformers.git
cd xformers
git submodule update --init --recursive
python -m venv venv
venv\scripts\activate
pip install --no-color torch==2.4.0+cu124 torchvision==0.19.0+cu124 --extra-index-url https://download.pytorch.org/whl/cu124
pip install --no-color -r requirements.txt
pip install --no-color wheel
set TORCH_CUDA_ARCH_LIST=8.9
set DISTUTILS_USE_SDK=1
python setup.py build
python setup.py bdist_wheel

## To Reproduce

1. Install Visual Studio 2022 17.11.1 with C++ Desktop Development workload
2. Install Python 3.11.9
3. Install CUDA toolkit 12.6
4. Use the commands above to build xformers from VS2022 x64 command prompt

```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\BUILD\xformers\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "C:\PROGRAMS\Python\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '12']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\BUILD\xformers\setup.py", line 558, in <module>
    setuptools.setup(
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\BUILD\xformers\setup.py", line 515, in build_extensions
    super().build_extensions()
  File "C:\BUILD\xformers\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 866, in build_extensions
    build_ext.build_extensions(self)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\BUILD\xformers\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BUILD\xformers\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 838, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\BUILD\xformers\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\BUILD\xformers\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
The stack trace doesn't seem to capture what's really going on, here are the relevent errors from build output before that traceback:
```
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(136): warning C4346: 'SharedStorage': dependent name is not a type
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(136): note: prefix the qualified-id with 'typename' to indicate a type
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(136): note: the template instantiation context (the oldest one first) is
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(60): note: while compiling class template partial specialization 'cutlass::gemm::kernel::GemmUniversal<ProblemShape_,CollectiveMainloop_,CollectiveEpilogue_,TileScheduler_,enable_if<std::is_base_of_v<cutlass::gemm::KernelTmaWarpSpecializedPingpong,CollectiveMainloop_::DispatchPolicy::Schedule>,void>::type>'
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(124): note: while compiling class 'cutlass::gemm::kernel::GemmUniversal<ProblemShape_,CollectiveMainloop_,CollectiveEpilogue_,TileScheduler_,enable_if<std::is_base_of_v<cutlass::gemm::KernelTmaWarpSpecializedPingpong,CollectiveMainloop_::DispatchPolicy::Schedule>,void>::type>::SharedStorage'
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(133): note: while compiling class 'cutlass::gemm::kernel::GemmUniversal<ProblemShape_,CollectiveMainloop_,CollectiveEpilogue_,TileScheduler_,enable_if<std::is_base_of_v<cutlass::gemm::KernelTmaWarpSpecializedPingpong,CollectiveMainloop_::DispatchPolicy::Schedule>,void>::type>::SharedStorage::PipelineStorage'
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(136): error C2061: syntax error: identifier 'SharedStorage'
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(140): error C3646: 'math_wg_order': unknown override specifier
C:/BUILD/xformers/third_party/cutlass/include\cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_pingpong.hpp(140): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

## Expected behavior

Build should finish successfully

## Environment

- PyTorch Version (e.g., 1.0): 2.4.0
- OS (e.g., Linux): Windows 11 (Version 10.0.22631.4037)
- How you installed PyTorch (`conda`, `pip`, source): see command
- Build command you used (if compiling from source): see command
- Python version: 3.11.9
- CUDA/cuDNN version: 12.6
- GPU models and configuration: RTX 4090
- Any other relevant information: This building method worked with all `xformers<=v0.0.27`

## Additional context

N/A

**Comment by lw** [comment]
The build failure seems to come from the CUTLASS submodule, not from xFormers itself.

Are you able to build CUTLASS as standalone? If not, you should report this in their GitHub repo.

My guess is that either you have an incompatible compiler, or your CUTLASS submodule is pinned to a bad commit.

Unfortunately we are not able to debug Windows issues on our side.

**Comment by danthe3rd** [comment]
Also the build process seems to work fine on the CI (https://github.com/facebookresearch/xformers/actions/runs/10469368653/job/28992253863), so it might be something with your setup. We have wheels for cu124 coming soon tho if that helps you

**Comment by levicki** [comment]
Hi, thanks for responding.

> The build failure seems to come from the CUTLASS submodule, not from xFormers itself.

So I have noticed.

> Are you able to build CUTLASS as standalone? If not, you should report this in their GitHub repo.

I have not tried that, I am only ever building it as part of this repo.

> My guess is that either you have an incompatible compiler, or your CUTLASS submodule is pinned to a bad commit.

 Compiler is the latest MSVC (Version 19.41.34120 for x64).

As for CUTLASS being pinned to a bad commit, how would that happen? Can you please confirm that the steps for compilation I used should result in a good commit being checked out from the submodule?

> so it might be something with your setup.

I am not ruling it out, but so far I was able to build using this setup.

> We have wheels for cu124 coming soon tho if that helps you

It might, but from your Windows part of CI it seems you aren't building with optimized path for Ada arch?
```
TORCH_CUDA_ARCH_LIST: 6.0+PTX 7.0 7.5 8.0+PTX
```
Unless 8.0+PTX is faster on RTX 4090 than 8.9?

**Comment by lw** [comment]
Use `git submodule update --init --recursive` to make sure the submodule pin didn't deviate from the main branch. If that still doesn't work, then it could be attributed to the fact that we updated the CUTLASS pin to version 3.5.0 recently. This would mean that CUTLASS has introduced a regression upstream.

**Comment by lw** [comment]
Also, maybe double-check that you don't have an existing installation on CUTLASS on your system, corresponding to a different version, which might cause a mix of conflicting headers being included by xFormers, thus causing issues. I don't know if MSVC has a way of printing which headers are used for each include.

**Comment by levicki** [comment]
> Use `git submodule update --init --recursive` to make sure the submodule pin didn't deviate from the main branch. If that still doesn't work, then it could be attributed to the fact that we updated the CUTLASS pin to version 3.5.0 recently. This would mean that CUTLASS has introduced a regression upstream.

I also tried using `git clone --recurse-submodules` (should be the same as `git submodule update ...`) and I end up on 3.5.0 with that when I clone xformers. I just checked out CUTLASS and I will try to build it using cmake.



> Also, maybe double-check that you don't have an existing installation on CUTLASS on your system, corresponding to a different version, which might cause a mix of conflicting headers being included by xFormers, thus causing issues. I don't know if MSVC has a way of printing which headers are used for each include.

Never installed CUTLASS at all.

Thanks for suggestions, I hope I will be able to figure it out.

**Comment by levicki** [comment]
Same problem building standalone CUTLASS 3.5.0 using Visual Studio and CMake.

Could you tell me what is the last xformers version which had a different pinned commit for CUTLASS?

**Comment by levicki** [comment]
@lw Can you please clarify whether setting `TORCH_CUDA_ARCH_LIST=8.9` is enough to build xformers (and subsequently CUTLASS) **only** for Ada Lovelace?

What I am getting at here is &mdash; what architectures does the xformers configure CUTLASS to build with? To me it seems that building 9.0 arch (Hopper) is what causes my build issue here. How can I control this? Is there something else I can set prior to running `python setup.py build` to force CUTLASS to build only for `sm_89`?

Please advise.

**Comment by levicki** [comment]
Maybe I am looking in the wrong place? There's CUTLASS code in `flash_attention/csrc/cutlass` which is two commits ahead from 3.5.0?

**Comment by levicki** [comment]
@lw https://github.com/facebookresearch/xformers/blob/7f42efbc1ea353a309bc7196050be72d0d03187f/setup.py#L236

**Comment by lw** [comment]
You can try to just comment out the `-std=c++17` option, since [PyTorch should be adding it on its own if missing](https://github.com/pytorch/pytorch/blob/57625baceacd0be1b6d16a57328de1a156512200/torch/utils/cpp_extension.py#L559-L566). Same with `-O3`: try replacing it with `-O2`. If this works we can fix it upstream.

Note that the problem occurs when including/parsing the CUTLASS headers, hence I doubt the target sm/arch matters here.

If you fail to build CUTLASS itself could you open an issue on their GitHub? They are the best placed to help.

**Comment by levicki** [comment]
I did try it (replaced with correct one):
```
post_cflags = -O2 -std:c++17 /MP /Zc:lambda /Zc:preprocessor /Zc:__cplusplus -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
```
Note that you are correct that `-std:c++17` gets added regardless of whether your `setup.py` adds it.

Sadly, aside from warnings it doesn't change the outcome &mdash; build still fails.

I have already opened an issue on CUTLASS (you can see it mentioned above).

I'd really like if I could isolate if this is the compiler problem or CUTLASS problem. Perhaps even `nvcc` could be the culprit.

**Comment by levicki** [comment]
@lw It's CUDA 12.6 &mdash; I reverted to 12.4.1 and it builds fine without any changes. I guess a bug report to NVIDIA for nvcc is in order.

**Comment by levicki** [comment]
@lw FYI, I reported this through my NVIDIA developer account. It's tracked as NVIDIA bug ID #[4820029](https://partners.nvidia.com/bug/viewbug/4820029). It's been reproduced internally and CUTLASS engineering team is investigating.

**Comment by Panchovix** [comment]
Just to bump a bit old thread, issue still persists. When I try to build with 12.6 it fails (using the Jan 2025 version), but 12.4 works, for torch built from source with CUDA 12.6.

Not sure if there is a major downside because of that, but seems to work.

**Comment by levicki** [comment]
@Panchovix Don't expect response anytime soon. They are apparently too busy making sure they have everything ready for 5000 series launch on January 21st. I highly doubt they will manage to do so because:

 - It's still holiday season in Asian countries
 - NVIDIA software support has traditionally lagged behind for one year behind flagship hardware

This might get fixed when they release CUDA for 5000 series cards.

**Comment by levicki** [comment]
I guess I was too hopeful.

Same error happens with CUDA 12.8 &mdash; in other words, still not a blip from NVIDIA on this.

This seems to be a CUDA compiler bug.

**Comment by levicki** [comment]
Ok the issue seems to be fixed with latest xformers referencing CUTLASS v3.8.0.
